In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_csv(r'/Users/edwincalderon/Desktop/M202A/open_thread_processed_data/logfile_ot_1m_process.csv')
df2 = pd.read_csv(r'/Users/edwincalderon/Desktop/M202A/open_thread_processed_data/logfile_ot_2m_process.csv')
df3 = pd.read_csv(r'/Users/edwincalderon/Desktop/M202A/open_thread_processed_data/logfile_ot_3m_process.csv')

In [3]:
print(min(df1['RSSI (dBm)'].unique()))
df1['RSSI (dBm)'].unique()

-68


array([  0, -66, -63, -64, -55, -65, -62, -57, -68, -67])

In [4]:
print(min(df2['RSSI (dBm)'].unique()))
df2['RSSI (dBm)'].unique()

-55


array(['0', 'rssi', '-61', '-56', '-55'], dtype=object)

In [5]:
print(min(df3['RSSI (dBm)'].unique()))
df3['RSSI (dBm)'].unique()

-65


array(['0', '0:', '-76', '-66', '-77', '-65', '-78', '-67', '-79'],
      dtype=object)

In [6]:
df1_ = pd.read_csv(r'/Users/edwincalderon/Desktop/M202A/ble_processed_data/logfile_1m_process.csv')
df2_ = pd.read_csv(r'/Users/edwincalderon/Desktop/M202A/ble_processed_data/logfile_2m_process.csv')
df3_ = pd.read_csv(r'/Users/edwincalderon/Desktop/M202A/ble_processed_data/logfile_3m_process.csv')

In [7]:
print(min(df1_['Measurement'].dropna().unique()))
df1_['Measurement'].dropna().unique()

-68.75


array([-13.25, -15.  , -26.25, -26.5 , -44.5 , -39.25, -38.75, -52.25,
       -51.25, -59.  , -51.5 , -61.75, -50.5 , -51.75, -52.5 , -65.  ,
       -50.  , -65.25, -49.75, -62.  , -49.  , -50.75, -52.  , -65.5 ,
       -53.5 , -66.  , -62.5 , -52.75, -54.25, -54.  , -61.25, -53.  ,
       -63.75, -55.  , -64.5 , -53.75, -54.5 , -55.5 , -56.  , -64.75,
       -57.75, -59.25, -62.25, -57.25, -58.  , -58.5 , -56.25, -56.75,
       -60.5 , -57.5 , -55.75, -58.75, -58.25, -57.  , -61.5 , -62.75,
       -56.5 , -59.5 , -66.25, -59.75, -68.25, -64.25, -55.25, -61.  ,
       -54.75, -66.5 , -67.5 , -64.  , -63.  , -68.5 , -65.75, -67.  ,
       -67.25, -63.25, -60.  , -66.75, -60.25, -68.75, -67.75, -63.5 ,
       -60.75])

In [8]:
print(min(df2_['Measurement'].dropna().unique()))
df2_['Measurement'].dropna().unique()

-68.75


array([  0.  , -14.75, -17.25, -28.5 , -17.5 , -33.25, -34.25, -50.25,
       -66.25, -51.  , -65.5 , -45.  , -66.75, -65.75, -60.25, -64.5 ,
       -61.  , -65.25, -60.75, -67.25, -68.5 , -61.75, -61.5 , -66.5 ,
       -67.5 , -68.  , -59.  , -66.  , -59.25, -57.75, -67.75, -60.5 ,
       -67.  , -63.  , -65.  , -62.  , -63.75, -61.25, -59.5 , -59.75,
       -57.  , -57.5 , -60.  , -62.25, -64.  , -58.5 , -62.75, -64.25,
       -62.5 , -64.75, -68.75, -63.25, -68.25, -63.5 , -58.75])

In [9]:
print(min(df3_['Measurement'].dropna().unique()))
df3_['Measurement'].dropna().unique()

-84.5


array([  0.  , -17.25, -33.75, -17.75, -19.75, -50.5 , -37.25, -66.75,
       -57.  , -74.25, -65.5 , -35.75, -53.5 , -74.5 , -66.  , -65.75,
       -76.5 , -75.25, -74.  , -66.25, -73.5 , -74.75, -67.  , -68.  ,
       -71.25, -70.25, -73.  , -67.5 , -75.5 , -75.75, -80.  , -78.25,
       -65.  , -76.25, -75.  , -73.25, -67.25, -79.5 , -79.75, -84.25,
       -73.75, -80.25, -76.  , -65.25, -64.75, -76.75, -78.75, -77.25,
       -66.5 , -71.  , -77.5 , -72.75, -72.5 , -71.5 , -80.5 , -67.75,
       -68.25, -72.  , -77.75, -77.  , -71.75, -68.5 , -79.  , -72.25,
       -81.  , -68.75, -69.  , -78.  , -81.25, -83.25, -78.5 , -69.25,
       -79.25, -82.  , -80.75, -82.5 , -69.75, -82.75, -70.75, -70.  ,
       -83.  , -84.5 , -81.75, -81.5 , -69.5 , -83.75])